name: Build Infrastructure

on:
  workflow_dispatch:  # Isso permite que você acione manualmente o fluxo de trabalho

jobs:
  build_native_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Build Environment
        run: |
          docker build -t graalvm-native-builder -f app/Dockerfile .

      - name: Prepare Deployment Package
        run: |
          cd app
          mv bootstrap .
          zip -j spring-native-function.zip bootstrap spring-native

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: lambda_deployment_package
          path: app/spring-native-function.zip

  terraform:
    needs: build_native_image  # Adiciona dependência do job anterior
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: lambda_deployment_package

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve