name: Build Infrastructure

on:
  workflow_dispatch:  # Isso permite que você acione manualmente o fluxo de trabalho

jobs:
  terraform:
    runs-on: amazonlinux2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

  build_native_image:
    runs-on: amazonlinux2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Build Environment
        run: |
          docker build -t graalvm-native-builder -f Dockerfile .

      - name: Run GraalVM Native Build in Docker
        run: |
          docker run --rm -v $(pwd):/workspace graalvm-native-builder /bin/bash -c "cd /workspace/app && ./mvnw -Pnative clean install -DskipTests"

      - name: Prepare Deployment Package
        run: |
          cd app
          mv bootstrap .
          zip -j spring-native-function.zip bootstrap spring-native

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: lambda_deployment_package
          path: app/spring-native-function.zip